2023-03-10 02:23:28,640 DEBUG: Trying to get LDAP data for user root [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-10 02:23:29,137 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-10 02:23:29,150 DEBUG: No such user root [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-10 02:23:39,383 DEBUG: Trying to get LDAP data for user falev [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-10 02:23:39,424 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-10 02:23:39,426 DEBUG: No such user falev [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-10 02:24:57,413 DEBUG: Trying to get LDAP data for user test_user [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-10 02:24:57,453 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-10 02:24:57,455 DEBUG: No such user test_user [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-10 02:35:27,992 DEBUG: Trying to get LDAP data for user asds [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-10 02:35:33,371 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-10 02:35:33,373 DEBUG: No such user asds [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-10 02:38:16,434 DEBUG: Trying to get LDAP data for user dsgf [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-10 02:38:16,491 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-10 02:38:16,493 DEBUG: No such user dsgf [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-10 02:40:18,482 DEBUG: Trying to get LDAP data for user sdds [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-10 02:40:18,660 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-10 02:40:18,662 DEBUG: No such user sdds [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-10 02:40:51,269 DEBUG: Trying to get LDAP data for user sdds [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-10 02:40:51,504 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-10 02:40:51,506 DEBUG: No such user sdds [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-10 02:40:53,470 DEBUG: Trying to get LDAP data for user sdfs [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-10 02:40:53,547 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-10 02:40:53,549 DEBUG: No such user sdfs [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-10 02:44:12,898 DEBUG: Trying to get LDAP data for user root [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-10 02:44:13,077 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-10 02:44:13,079 DEBUG: No such user root [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-12 21:49:27,826 DEBUG: Trying to get LDAP data for user asdsad [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-12 21:49:27,890 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-12 21:49:27,893 DEBUG: No such user asdsad [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-12 22:06:31,405 DEBUG: Trying to get LDAP data for user asdsad [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-12 22:06:31,429 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-12 22:06:31,431 DEBUG: No such user asdsad [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-12 22:06:40,345 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:06:40,376 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:07:49,695 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:07:49,731 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:07:54,323 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:07:54,359 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:08:07,499 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:08:07,536 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:08:44,752 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:08:44,789 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:13:56,391 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:13:56,421 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:14:24,147 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:14:34,782 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-12 22:29:09,581 DEBUG: News with id 3 is being edited [in /home/filya/TPPO/web/imit/controllers/news.py:102]
2023-03-12 22:38:54,724 DEBUG: News with id 1 is being deleted [in /home/filya/TPPO/web/imit/controllers/news.py:139]
2023-03-12 23:19:38,480 DEBUG: Trying to get LDAP data for user asd [in /home/filya/TPPO/web/imit/models.py:215]
2023-03-12 23:19:38,545 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:230]
2023-03-12 23:19:38,547 DEBUG: No such user asd [in /home/filya/TPPO/web/imit/models.py:261]
2023-03-12 23:22:59,645 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-19 18:33:04,382 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-19 18:34:00,180 DEBUG: Adding cover image to news 4 [in /home/filya/TPPO/web/imit/controllers/news.py:152]
2023-03-19 18:34:00,181 DEBUG: Storing images ci_4.png and ci_4_full.jpg to drive [in /home/filya/TPPO/web/imit/controllers/news.py:160]
2023-03-19 18:34:00,182 ERROR: Error ocurried during cover image file saving: [Errno 2] No such file or directory: 'imit/static/files/covers/ci_4.png' [in /home/filya/TPPO/web/imit/controllers/news.py:165]
2023-03-19 18:34:18,254 DEBUG: File is being added [in /home/filya/TPPO/web/imit/controllers/main.py:180]
2023-03-19 18:34:21,030 DEBUG: News with id 4 is being edited [in /home/filya/TPPO/web/imit/controllers/news.py:102]
2023-03-19 18:34:33,530 DEBUG: File is being edited [in /home/filya/TPPO/web/imit/controllers/main.py:216]
2023-03-19 18:34:52,383 DEBUG: News with id 4 is being edited [in /home/filya/TPPO/web/imit/controllers/news.py:102]
2023-03-19 18:34:52,387 DEBUG: Adding cover image to news 4 [in /home/filya/TPPO/web/imit/controllers/news.py:152]
2023-03-19 18:34:52,387 DEBUG: Storing images ci_4.png and ci_4_full.jpg to drive [in /home/filya/TPPO/web/imit/controllers/news.py:160]
2023-03-19 18:34:52,387 ERROR: Error ocurried during cover image file saving: [Errno 2] No such file or directory: 'imit/static/files/covers/ci_4.png' [in /home/filya/TPPO/web/imit/controllers/news.py:165]
2023-03-19 19:11:50,641 DEBUG: News with id 4 is being deleted [in /home/filya/TPPO/web/imit/controllers/news.py:139]
2023-03-19 19:11:52,791 DEBUG: News with id 3 is being deleted [in /home/filya/TPPO/web/imit/controllers/news.py:139]
2023-03-19 19:11:53,886 DEBUG: News with id 2 is being deleted [in /home/filya/TPPO/web/imit/controllers/news.py:139]
2023-03-19 19:12:37,714 DEBUG: Adding cover image to news 5 [in /home/filya/TPPO/web/imit/controllers/news.py:152]
2023-03-19 19:12:37,714 DEBUG: Storing images ci_5.png and ci_5_full.jpg to drive [in /home/filya/TPPO/web/imit/controllers/news.py:160]
2023-03-19 19:12:37,715 ERROR: Error ocurried during cover image file saving: [Errno 2] No such file or directory: 'imit/static/files/covers/ci_5.png' [in /home/filya/TPPO/web/imit/controllers/news.py:165]
2023-03-19 19:12:58,091 DEBUG: File is being added [in /home/filya/TPPO/web/imit/controllers/main.py:180]
2023-03-19 19:13:04,411 DEBUG: File is being edited [in /home/filya/TPPO/web/imit/controllers/main.py:216]
2023-03-19 19:13:07,932 DEBUG: News with id 5 is being edited [in /home/filya/TPPO/web/imit/controllers/news.py:102]
2023-03-19 19:51:04,477 ERROR: Invalid json input [in /home/filya/TPPO/web/imit/controllers/faq.py:22]
2023-03-19 20:10:45,079 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
2023-03-19 20:15:15,921 ERROR: LDAP error: invalid server address [in /home/filya/TPPO/web/imit/models.py:279]
